parameters:

    wxr_geo.translation_domain: WXRGeoBundle

services:

    wxr_geo.admin.country:
        class: WXR\GeoBundle\Admin\Entity\CountryAdmin
        arguments: [ ~, WXR\GeoBundle\Entity\Country, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: countries
                label_catalogue: WXRGeoBundle
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_geo.admin.region:
        class: WXR\GeoBundle\Admin\Entity\RegionAdmin
        arguments: [ ~, WXR\GeoBundle\Entity\Region, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: regions
                label_catalogue: WXRGeoBundle
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_geo.admin.city:
        class: WXR\GeoBundle\Admin\Entity\CityAdmin
        arguments: [ ~, WXR\GeoBundle\Entity\City, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: cities
                label_catalogue: WXRGeoBundle
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_geo.admin.location:
        class: WXR\GeoBundle\Admin\Entity\LocationAdmin
        arguments: [ ~, WXR\GeoBundle\Entity\Location, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: locations
                label_catalogue: WXRGeoBundle
                label_translator_strategy: sonata.admin.label.strategy.underscore
