services:
    wxr_geo.admin.country:
        class: WXR\GeoBundle\Admin\Entity\CountryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: wxr_geo.geo, label: wxr_geo..country.country }
        arguments: [ ~, WXR\GeoBundle\Entity\Country, SonataAdminBundle:CRUD ]

    wxr_geo.admin.region:
        class: WXR\GeoBundle\Admin\Entity\RegionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: wxr_geo.geo, label: wxr_geo.region.region }
        arguments: [ ~, WXR\GeoBundle\Entity\Region, SonataAdminBundle:CRUD ]

    wxr_geo.admin.city:
        class: WXR\GeoBundle\Admin\Entity\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: wxr_geo.geo, label: wxr_geo.city.city }
        arguments: [ ~, WXR\GeoBundle\Entity\City, SonataAdminBundle:CRUD ]

    wxr_geo.admin.location:
        class: WXR\GeoBundle\Admin\Entity\LocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: wxr_geo.geo, label: wxr_geo.location.location }
        arguments: [ ~, WXR\GeoBundle\Entity\Location, SonataAdminBundle:CRUD ]
