services:

    wxr_geo.city.default_manager:
        class: WXR\GeoBundle\Entity\LocationManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.city.class%]

    wxr_geo.city.form:
        factory_service: form.factory
        factory_method: create
        class: Symfony\Component\Form\Form
        arguments: [ @wxr_geo.city.form.type ]

    wxr_geo.city.form.default_type:
        class: WXR\GeoBundle\Form\Type\CityType
        arguments: [ %wxr_geo.city.class% ]

    wxr_geo.city.form.default_handler:
        class: WXR\GeoBundle\Form\Handler\CityHandler
        scope: request
        arguments: [ @request, @wxr_geo.city.form, @wxr_geo.city.manager ]
