parameters:

    wxr_geo.country.class: Application\WXR\GeoBundle\Entity\Country
    wxr_geo.region.class: Application\WXR\GeoBundle\Entity\Region
    wxr_geo.city.class: Application\WXR\GeoBundle\Entity\City
    wxr_geo.address.class: Application\WXR\GeoBundle\Entity\Address

services:

    wxr_geo.country.manager.default:
        class: WXR\GeoBundle\Entity\CountryManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.country.class%]

    wxr_geo.country.admin:
        class: %wxr_geo.country.admin.class%
        arguments: [ ~, %wxr_geo.country.class%, %wxr_geo.country.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
            - [ setTemplate, [ edit, WXRGeoBundle:CRUD:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: countries
                label_catalogue: %wxr_geo.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_geo.region.manager.default:
        class: WXR\GeoBundle\Entity\RegionManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.region.class%, %wxr_geo.country.class%]

    wxr_geo.region.admin:
        class: %wxr_geo.region.admin.class%
        arguments: [ ~, %wxr_geo.region.class%, %wxr_geo.region.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
            - [ setTemplate, [ edit, WXRGeoBundle:CRUD:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: regions
                label_catalogue: %wxr_geo.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_geo.city.manager.default:
        class: WXR\GeoBundle\Entity\CityManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.city.class%]

    wxr_geo.city.admin:
        class: %wxr_geo.city.admin.class%
        arguments: [ ~, %wxr_geo.city.class%, %wxr_geo.city.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
            - [ setTemplate, [ edit, WXRGeoBundle:CRUD:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_geo
                label: cities
                label_catalogue: %wxr_geo.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_geo.address.manager.default:
        class: WXR\GeoBundle\Entity\AddressManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.address.class%]

    wxr_geo.address.admin:
        class: %wxr_geo.address.admin.class%
        arguments: [ ~, %wxr_geo.address.class%, %wxr_geo.address.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_geo.translation_domain% ] ]
            - [ setTemplate, [ edit, WXRGeoBundle:CRUD:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                show_in_dashboard: false
                manager_type: orm
                group: wxr_geo
                label: addresses
                label_catalogue: %wxr_geo.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore
