WXR\GeoBundle\Entity\Location:
    type: entity
    table: wxr_geo_location
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        street:
            type: string
            length: 255
        latitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
        longitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
    manyToOne:
        city:
            targetEntity: City
            inversedBy: locations
            joinColumn:
                name: city_id
                referencedColumnName: id
                onDelete: SET NULL
